-- Phase 3, step 2: create the four descriptive dimension tables.
-- Run this file with psql after 01_create_database.sql.
-- This file creates structure only; it does not insert or load any rows.

\set ON_ERROR_STOP on
\if :{?warehouse_db}
\else
\set warehouse_db central_superstore_dw
\endif
\connect :warehouse_db

-- FactSales depends on the dimensions, so remove it before removing dimensions.
-- This also makes a full rerun of the ordered scripts safe.
DROP TABLE IF EXISTS warehouse."FactSales";
DROP TABLE IF EXISTS warehouse."DimLocation";
DROP TABLE IF EXISTS warehouse."DimProduct";
DROP TABLE IF EXISTS warehouse."DimCustomer";
DROP TABLE IF EXISTS warehouse."DimDate";

-- Each date gets a deterministic YYYYMMDD primary key rather than a sequence.
CREATE TABLE warehouse."DimDate" (
    "DateKey" INTEGER PRIMARY KEY,
    "FullDate" DATE NOT NULL,
    "Year" SMALLINT NOT NULL,
    "Quarter" SMALLINT NOT NULL,
    "Month" SMALLINT NOT NULL,
    "MonthName" VARCHAR(12) NOT NULL,
    "Day" SMALLINT NOT NULL,
    "DayOfWeek" VARCHAR(12) NOT NULL,
    -- A true value marks Saturday or Sunday for simple weekend reporting.
    "IsWeekend" BOOLEAN NOT NULL
);

-- CustomerKey is a warehouse-generated identifier; CustomerID is the source key.
CREATE TABLE warehouse."DimCustomer" (
    "CustomerKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerID" VARCHAR(20) NOT NULL,
    "CustomerName" TEXT NOT NULL,
    "Segment" VARCHAR(30) NOT NULL
);

-- ProductKey distinguishes source product members, including name variants.
CREATE TABLE warehouse."DimProduct" (
    "ProductKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductID" VARCHAR(30) NOT NULL,
    "ProductName" TEXT NOT NULL,
    "Category" VARCHAR(50) NOT NULL,
    "SubCategory" VARCHAR(50) NOT NULL
);

-- Postal codes are stored as text because they identify places, not quantities.
CREATE TABLE warehouse."DimLocation" (
    "LocationKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Country" VARCHAR(100) NOT NULL,
    "State" VARCHAR(100) NOT NULL,
    "City" VARCHAR(100) NOT NULL,
    "PostalCode" VARCHAR(20) NOT NULL,
    "Region" VARCHAR(50) NOT NULL
);