-- Phase 3, step 3: create the central order-line fact table.
-- Run this file with psql after 02_create_dimensions.sql.
-- No source or test data is inserted by this script.

\set ON_ERROR_STOP on
\if :{?warehouse_db}
\else
\set warehouse_db central_superstore_dw
\endif
\connect :warehouse_db

-- Remove an earlier fact table before recreating it for an ordered rerun.
DROP TABLE IF EXISTS warehouse."FactSales";

-- One row will represent one product line in one order.
CREATE TABLE warehouse."FactSales" (
    "SalesKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceRowID" INTEGER NOT NULL,
    "OrderID" VARCHAR(30) NOT NULL,
    "OrderDateKey" INTEGER NOT NULL,
    "ShipDateKey" INTEGER NOT NULL,
    "CustomerKey" INTEGER NOT NULL,
    "ProductKey" INTEGER NOT NULL,
    "LocationKey" INTEGER NOT NULL,
    "ShipMode" VARCHAR(30) NOT NULL,
    "Sales" NUMERIC(14, 4) NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "Discount" NUMERIC(5, 4) NOT NULL,
    "Profit" NUMERIC(14, 4) NOT NULL
);